drop table IF EXISTS users CASCADE;
drop table IF EXISTS status CASCADE;
drop table IF EXISTS applications CASCADE;

    create table if not exists users (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id)
    );

     create table if not exists roles (
   id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR (255) NOT NULL,
   CONSTRAINT pk_role PRIMARY KEY (id)
   );


    create table if not exists applications (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(1024) NOT NULL,
  user_id INTEGER REFERENCES users (id),
  status_application VARCHAR(12) NOT NULL,
  time_create TIMESTAMP NOT NULL,
  CONSTRAINT pk_applications PRIMARY KEY (id)
  );

  create table if not exists us_role (
  user_id INTEGER,
  role_id INTEGER,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users (id),
  FOREIGN KEY (role_id) REFERENCES roles (id);

   insert into roles (id, name) values  (1, 'ROLE_OPERATOR'), (2, 'ROLE_USER'), (3, 'ROLE_ADMIN');
   insert into users (name, email) values ('dasha', 'saffs@r.com'), ('valy', 'htpppf@y.com'), ('lea', 'tom@w.com');
   insert into us_role (user_id, role_id) values (1, 2), (1, 1), (2, 2), (3, 3);