drop table IF EXISTS users CASCADE;
drop table IF EXISTS status CASCADE;
drop table IF EXISTS applications CASCADE;

    create table if not exists users (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id)
    );

     create table if not exists status (
   id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id INTEGER NOT NULL REFERENCES users (id),
   status_name VARCHAR (255) NOT NULL,
   CONSTRAINT pk_status PRIMARY KEY (id)
   );

    create table if not exists applications (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(1024) NOT NULL,
  user_id INTEGER REFERENCES users (id),
  status_application VARCHAR(12) NOT NULL,
  time_create TIMESTAMP NOT NULL,
  CONSTRAINT pk_applications PRIMARY KEY (id)
  );

   insert into users (name, email) values ('dasha', 'saffs@r.com'), ('valy', 'htpppf@y.com'), ('lea', 'tom@w.com');
   insert into status (user_id, status_name) values (1, 'CUSTOMER'), (1, 'OPERATOR'), (2, 'CUSTOMER'), (3, 'ADMINISTRATOR');

